### PR TITLE
Added Enter as a multipurpose action

### PR DESCRIPTION
**Pull request by andreadev-it**
This PR makes the Enter key a multipurpose key. It will do a different action based on the context.
It currently overrides the "org_return" action and checks for these situations (in this specific order):
- open links
- open dates in calendar
- change headline status
- toggle a list item

Otherwise, it will do the "org_return" action as a default.

I've made this PR as a way to discuss this, as proposed in #301 

Some things I'd like to discuss are:
- Should we be using this as the default action for the Enter key? It seems to be like this on Emacs, but honestly, I had only tried it in Doom Emacs, not the vanilla one, if I recall correctly.
- The order in which the actions are checked is ok? It seemed sensible to me.
- What to do about the "org_return" / "use original return" actions? Should we keep these as is?

Thank you for your time, as always, I'm open to suggestions, have a nice day

### CODE REVIEW

**Comment by andreadev-it** [comment]
I've seen that my PR is failing with an error about generating a new table row when the Enter key is pressed. I've tried it, but this feature doesn't seem to exists even in the official plugin... I've tried with the table-mode plugin either enabled and disabled on the official master branch.

**Comment by jgollenz** [comment]
> What to do about the "org_return"

@kristijanhusak please refresh my memory: what was the reason for adding `org_return`?

> The order in which the actions are checked is ok

also seems sensible to me

> Should we be using this as the default action for the Enter key?

If it is this way in vanilla Emacs, we probably should have it here as well

**Comment by kristijanhusak** [comment]
@jgollenz It was added when we added support for tables, to reformat the table when you press Return.
@andreadev-it  I think we should just add all this logic to `org_return` because your code doesn't handle fallback to the old "<CR>" mapping.

**Comment by andreadev-it** [comment]
I'm looking at it and managed to merge my code with the one from the original org_return. But there seems to be a catch: the org_return function will be executed while in insert mode. This multipurpose action should (in my opinion) only available in normal mode. Is it still fine to merge them? It seems like they should be separated, with "org_return" for insert mode and "multipurpose_action" for normal mode...

**Comment by kristijanhusak** [comment]
> But there seems to be a catch: the org_return function will be executed while in insert mode. This multipurpose action should (in my opinion) only available in normal mode. Is it still fine to merge them? It seems like they should be separated, with "org_return" for insert mode and "multipurpose_action" for normal mode...

My mistake then. `org_return` is insert mode mapping, and should not be removed. AFAIK Emacs Orgmode doesn't have this idea of a multipurpose Return mapping, so I'm not sure it should be part of the core. 

> Should we be using this as the default action for the Enter key? It seems to be like this on Emacs, but honestly, I had only tried it in Doom Emacs, not the vanilla one, if I recall correctly

Emacs doesn't have a normal mode, at least not without Evil mode. How does Return behave with Evil when you press it in normal mode in Emacs?

**Comment by kristijanhusak** [comment]
Do you know if that functionality is part of evil mode or part of Doom Emacs?

**Comment by andreadev-it** [comment]
Since it doesn't seem that this functionality was implemented by default in orgmode, I've decided to create a plugin to add it instead. If you guys agree that this is the correct way to do it, you can close this PR.

Here is a link to the plugin: https://github.com/andreadev-it/orgmode-multi-key

@kristijanhusak

**Comment by kristijanhusak** [comment]
I guess it's ok for now to have it as a separate plugin. We could maybe have it also in here, but we need to have tests passing and this option being somehow opt-in.

**Comment by jgollenz** [comment]
@andreadev-it is it ok to close this PR for now?

**Comment by andreadev-it** [comment]
Yes, I agree to close it for now.

**Pull request closed without merging**
