### PR TITLE
WIP: Feat/which key descriptions

### LINKED ISSUE #314: Add desc to orgmode keymap
### Does this feature exist in Emacs orgmode core?

N/A

### Orgmode link

_No response_

### Feature value

Which Key access the "desc" property to display set keymaps
it would be great to have proper descriptions for orgmode mappings
```lua
vim.keymap.set(mode, command, { desc = "Description of the mapping" })
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jgollenz**
closes #314

### TODO
- [x] multi-key rebinding
- [x] basic rebinding (user passes a string, not a table)
- [ ] discuss descriptions

### CODE REVIEW

**Comment by jgollenz** [comment]
@kristijanhusak this should work. I need some confirmation on the descriptions I added

**Comment by kristijanhusak** [comment]
Descriptions look fine, I just don't know if `which-key` gives some context around mappings? If a mapping has description `Earlier`, will user see something like `Orgmode - Earlier` or something like that?

**Comment by jgollenz** [comment]
> I just don't know if which-key gives some context around mappings? If a mapping has 
> description Earlier, will user see something like Orgmode - Earlier or something like that?

Hm, it doesn't look like that is possible via `opts.desc` alone. It is possible to explicitly markup `o` (or whatever) with `orgmode`. Mappings with multiple keys for lhs, are organized in a tree structure:

which-key

If nothing is declared for `o` or `oi` it will be displayed as `+prefix`. So no implicit context, unless we specify it

**Comment by kristijanhusak** [comment]
> So no implicit context, unless we specify it

Ok, lets add it. I think it will be more useful if users know the context, especially if they override some of the `<Leader>o` mappings.

**Comment by kristijanhusak** [comment]
These mappings are really starting to complicate. Lets hold on this for a bit, I'll rewrite it today so it's more readable and testable. I'm worried we will break something with these changes.

**Comment by jgollenz** [comment]
> These mappings are really starting to complicate

Absolutely. It's special cases galore. Didn't want to introduce any breaking changes, that's why I did it this way. Ideally, all the mappings have the same format. Right now there is ~5 different ways to do it

**Comment by jgollenz** [comment]
And as can be seen with the help overlay, things are already starting to break

**Comment by jgollenz** [comment]
new PR is #352

**Pull request closed without merging**
