### PR TITLE
Add basic `org-insert-link` functionality

### PR DESCRIPTION
**Pull request by jgollenz**
Described [here](https://orgmode.org/manual/Handling-Links.html#index-C_002dc-C_002dl)

There is no completion support for protocols (`http`, etc.) yet.

In light of other GH issues that are concerned with hyperlinks I'd like to discuss whether it makes sense to add a hyperlink object. It would possibly ease development in the future. Also, how about parsing them? Opening hyperlinks from the agenda requires to display all the links of a headline body to the user. There is also [`org-[next|previous]-link`](https://orgmode.org/manual/Handling-Links.html#index-C_002dc-C_002dl), that jumps to the next|previous link in the buffer

### CODE REVIEW

**Comment by kristijanhusak** [comment]
> In light of other GH issues that are concerned with hyperlinks I'd like to discuss whether it makes sense to add a hyperlink object. It would possibly ease development in the future. Also, how about parsing them?

I definitely support this. Regarding the parsing, we can probably do parsing only when necessary, not on init.

**Comment by jgollenz** [comment]
> I definitely support this

Great :slightly_smiling_face: I'll prepare another PR for it.

> do parsing only when necessary

Sounds sensible. It's also large enough to do it in a dedicated PR imo.

Is there anything left for this PR?

**Comment by jgollenz** [comment]
@kristijanhusak ping

**Review by kristijanhusak — APPROVED** [review]
Looks good! Thanks!

And sorry for delay.

**Comment by Maltimore** [comment]
@jgollenz the mapping for `insert-link` does not appear in the list of mappings that I get by pressing `g?` in an org file. Is that on purpose?
A small but fantastic feature by the way, thanks :)

**Comment by Maltimore** [comment]
@jgollenz sorry to bother you again. I noticed that, similar to inserting time stamps, the link is inserted before the cursor and not after. I would find it more intuitive if the link was inserted after the cursor, for the same reasons as the time-stamps (i.e., usually you write some text, then enter a space, and then you'd like to have a link after the space. Currently you have to enter two spaces and then enter the link and then remove one of the spaces again.

**Comment by jgollenz** [comment]
> Is that on purpose?

of course not :grin:

> more intuitive if the link was inserted after the cursor

I agree. Please check [this branch](https://github.com/jgollenz/orgmode/tree/fix/insert-link-after-cursor). Does it work as expected?

**Comment by Maltimore** [comment]
Works like a charm! Thank you! :)

**Pull request merged**
