### PR TITLE
Aligning tags

### LINKED ISSUE #389: Aligning tags
### Does this feature exist in Emacs orgmode core?

N/A

### Orgmode link

Is there any function that can be called to realign tags to the defined margin? When manually adding tags by just typing the keywords `:TAG1:TAG2:` or the like it's cumbersome to align them with the other tags. Would be great if there would be an easy way to realign tags in a document or marked area.

### Feature value

Ease of use and better visuals

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jgollenz**
fixes #389 

- [x] align after promotion, demotion and TODO state change
- [ ] add mapping to align all tags in file
- [ ] unit tests

### CODE REVIEW

**Comment by kristijanhusak** [comment]
@jgollenz you can either rebase and continue working on this to add alignments where you think it's missing by setting up an event, or you can close it and create a new PR if needed.

**Comment by jgollenz** [comment]
I'll rebase it. The only thing missing is the mapping that aligns all the tags in the buffer. I'm trying to do this with a treesitter query (`util.get_ts_matches('(headline (tag_list))'`), but I'm still struggling with that

**Comment by kristijanhusak** [comment]
What mapping have you planned to use? Since this is basically a formatting action, I think we should use `formatexpr` that is bind to `gq`. There's already a [formatexpr handler](https://github.com/nvim-orgmode/orgmode/blob/master/lua/orgmode/org/format.lua) for tables and clock times, so I think for now you can just add it in here by checking if current line starts with `*`, and if yes, call the `ts_org.closest_headline():align_tags()`. You can add it before last return, and return 0 if formatting was done. Doing it through global query is probably more difficult, and logic would be potentially split in 2 places.

**Comment by jgollenz** [comment]
Ah, this makes sense, thanks! Emacs does it for the whole buffer, what would be the equivalent for that? `gq%`?

**Comment by kristijanhusak** [comment]
`gq` behaves like `=`, which means that it's probably `gggqG`. I don't know if there's a shorter version.

**Comment by jgollenz** [comment]
I added 

```
  if vim.fn.getline(line):match('^%*') then
    ts_org.closest_headline():align_tags()
    return 0
  end
```

and it works fine if I just select a single line in visual mode. But it breaks gloriously if I select multiple lines, especially if there are empty lines before the first heading with tags.

**Comment by kristijanhusak** [comment]
`formatexpr` is not working as I expected when I initially added it. While testing this I found few bugs and rewrote the `formatexpr` to work. I also added a support for aligning tags, so this PR became obsolete, sorry. You can pull latest master and give it atry.

**Comment by jgollenz** [comment]
huh, interesting. `vim.v.count` always returns zero for me :man_shrugging: anyway, glad its finally working :grinning:

**Comment by kristijanhusak** [comment]
That's because there was a bug in `Table.format` which messed up the line numbering for some reason (`norm! _` caused the issue).

**Comment by jgollenz** [comment]
Ah, I see. We should document this feature

**Comment by kristijanhusak** [comment]
We have few mentions of `gq` in the docs for tables and clock values, but I guess we should unify it in one section.

**Comment by kristijanhusak** [comment]
I added some basic explanation here https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#formatting, should be ok for now.

**Pull request closed without merging**
