### PR TITLE
Match by category

### PR DESCRIPTION
**Pull request by chuck-flowers**
Allows a user to match using the implicit `CATEGORY` property as mentioned in org's
documentation [here](https://orgmode.org/manual/Categories.html)

### CODE REVIEW

**Comment by chuck-flowers** [comment]
@kristijanhusak if you have a moment can you take a look at this? It's a very small change that would improve my workflow. I currently have several PRs open so it's difficult for me to simply reference this branch, and give up the features from my other larger PRs.

**Comment by kristijanhusak** [comment]
This will actually override the category set in the properties of a headline, which should have precedence over file category. It's best to create the props hash and then override category only if it's not set.

**Comment by chuck-flowers** [comment]
I've updated the code to use `keep` instead of `force`. This will force the search logic to favor what's contained within properties instead of what I'm pulling from the section itself.

**Review by kristijanhusak — APPROVED** [review]

**Comment by kristijanhusak** [comment]
Thanks!

**Pull request merged**
