### PR TITLE
Adds :itoday: and :inow: abbreviations

### PR DESCRIPTION
**Pull request by chuck-flowers**
Adds two additional abbreviations that allow users to easily insert the
current date or time as an inactive timestamp.

### CODE REVIEW

**Comment by jgollenz** [comment]
We also could do this: 
```
inoreabbrev <silent><buffer> :today: <C-R>=luaeval("require('orgmode.objects.date').today():to_wrapped_string(true)")<CR>
inoreabbrev <silent><buffer> :now: <C-R>=luaeval("require('orgmode.objects.date').now():to_wrapped_string(true)")<CR>
inoreabbrev <silent><buffer> :itoday: <C-R>=luaeval("require('orgmode.objects.date').now():to_wrapped_string(false)")<CR>
inoreabbrev <silent><buffer> :inow: <C-R>=luaeval("require('orgmode.objects.date').now():to_wrapped_string(false)")<CR>
```

I think it makes things a bit clearer, if one looks at the signature of `to_wrapped_string`. Anyhow, we should add a comment what `inow/itoday` stands for

**Comment by jgollenz** [comment]
But then again, it's just a fancy way of doing the same thing with an additional performance cost :man_shrugging:

**Comment by chuck-flowers** [comment]
I like yours better. I think it's a bit easier to see what's going on that way. I'll update now.

**Comment by chuck-flowers** [comment]
Sorry, I forced push to my branch to amend the commit but apparently GitHub didn't like that. I'll have to open a new PR

**Pull request closed without merging**
