### PR TITLE
Reformat docs

### PR DESCRIPTION
**Pull request by seflue**
- reformat markdown files
- replace md2vim with panvimdoc

### CODE REVIEW

**Comment by seflue** [comment]
@kristijanhusak On my fork the document action does  not work because of wrong access token. To test the pipeline, it would be helpful if you could just push this branch to the nvim-orgmode repo (I don't have the permissions to do so).

**Review by kristijanhusak — APPROVED** [review]

**Comment by kristijanhusak** [comment]
Thanks @seflue ! I'm merging this in to see if it works fine. What are you using for formatting markdown?

**Comment by seflue** [comment]
> Thanks @seflue ! I'm merging this in to see if it works fine. What are you using for formatting markdown?

Honestly, I'm not sure, which one kicks in, when I hit safe, but I guess it's prettier, which I am using via none-ls.

**Comment by kristijanhusak** [comment]
TBH I'm not really liking the output of the new docs. Table of content is messed up, there are no tags on each heading. I'll if I can do something to make it better.

**Comment by kristijanhusak** [comment]
I reverted doc generating back to md2vim until the doc file is migrated to org format.

**Comment by seflue** [comment]
> TBH I'm not really liking the output of the new docs. Table of content is messed up, there are no tags on each heading. I'll see if I can do something to make it better.

I agree. To get it clean it would need some hand work on the Markdown. How the syntax is interpreted and tags are generated is documented, so there are good options but it would need work. Because you're aiming to migrate the Docs to Orgmode anyway, it makes absolute sense to defer the manual work to get the Orgmode right.

If you won't mind to give me permissions to push feature branches in nvim-orgmode, I would be happy to experiment a little bit. I would actually do it on my fork, but there are issues with GitHub tokens and GH Actions on forked repositories.

**Comment by kristijanhusak** [comment]
> If you won't mind to give me permissions to push feature branches in nvim-orgmode

I'm not sure how to do that. You should be able to add your own GH token on your fork to make it work.
You can also use `panvimdoc` directly by cloning it and using an `.sh` file. That's how I tested it.

**Pull request merged**
