### PR TITLE
fix: links with relative path to parent directories

### PR DESCRIPTION
**Pull request by seflue**
Fixed headline autocompletion and jumping to files in parent or sibling directories. See also [org-open-at-point](https://orgmode.org/org.html#index-C_002dc-C_002do) in the Org manual. It solves issue [#583](https://github.com/nvim-orgmode/orgmode/issues/583).

### CODE REVIEW

**Comment by seflue** [comment]
I don't understand, why the tests do not run. I get a an error, that treesitter could not be found, when I try to run the tests locally. But I don't know, how this is supposed to work.
```
Error detected while processing /home/seflue/projects/nvim-orgmode/tests/minimal_init.vim:
line   21:
E5108: Error executing lua ./lua/orgmode/init.lua:69: module 'nvim-treesitter.parsers' not found:
        no field package.preload['nvim-treesitter.parsers']
        no file './nvim-treesitter/parsers.lua'
        no file '/usr/share/luajit-5_1-2.1.0-beta3/nvim-treesitter/parsers.lua'
        no file '/usr/local/share/lua/5.1/nvim-treesitter/parsers.lua'
        no file '/usr/local/share/lua/5.1/nvim-treesitter/parsers/init.lua'
        no file '/usr/share/lua/5.1/nvim-treesitter/parsers.lua'
        no file '/usr/share/lua/5.1/nvim-treesitter/parsers/init.lua'
        no file './nvim-treesitter/parsers.so'
        no file '/usr/local/lib/lua/5.1/nvim-treesitter/parsers.so'
        no file '/usr/lib64/lua/5.1/nvim-treesitter/parsers.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './nvim-treesitter.so'
        no file '/usr/local/lib/lua/5.1/nvim-treesitter.so'
        no file '/usr/lib64/lua/5.1/nvim-treesitter.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        ./lua/orgmode/init.lua:69: in function 'setup_ts_grammar'
        [string ":lua"]:1: in main chunk
Error detected while processing command line:
E492: Not an editor command: TSUpdateSync org
E492: Not an editor command: PlenaryBustedDirectory tests/plenary/ {minimal_init = 'tests/minimal_init.vim'}
```

**Comment by kristijanhusak** [comment]
Did you install all dependencies? Here are instructions how to set up https://github.com/nvim-orgmode/orgmode/blob/master/CONTRIBUTING.md#tests

**Comment by jgollenz** [comment]
@seflue could you please add a link to the emacs orgmode docs for the feature / bug you are addressing? Thanks

**Comment by seflue** [comment]
> Did you install all dependencies? Here are instructions how to set up https://github.com/nvim-orgmode/orgmode/blob/master/CONTRIBUTING.md#tests

My fault, I just found the instructions. Is it normal, that I have to stop the process with Ctrl-C after the tests ran? Or should it jump right back into console (what I would have expected)?

**Comment by seflue** [comment]
> @seflue could you please add a link to the emacs orgmode docs for the feature / bug you are addressing? Thanks

The feature is [org-open-at-point](https://orgmode.org/org.html#index-C_002dc-C_002do). Should I update the commit message?

**Comment by jgollenz** [comment]
> Should I update the commit message?

No, just a link to the orgmode manual / docs is sufficient. I presume this PR closes #583?

**Comment by seflue** [comment]
I was able to find the reason why the tests broke. Within the autocompletion test the function using `vim.loop.fs_realpath` is used - therefore it has to be mocked.

**Review by kristijanhusak — APPROVED** [review]
This looks ok to me, thanks!

**Pull request merged**
