### PR TITLE
Fix broken priority cycling

### LINKED ISSUE #382: Priority Cycling broken when prio-state above 9
### Describe the bug

When due to custom values for `org_priority_[highest|lowest]` a prio-state above 9 becomes a valid state, the cycling is broken. See the gif.

### Steps to reproduce

- open a buffer with the provided `minimal_lua.init`
- enter `cir` on a headline until you reach a prio-state above 9 

### Expected behavior

According to [this](https://orgmode.org/manual/Priorities.html) prio-states up to 64 are valid. I highly suspect this is because 65 is the ASCII code for `A`. If we want to replicate this, we should add it to the docs.

### Emacs functionality

~~It appears, that vanilla orgmode is also buggy here, but the behavior is different. Try setting `#+PRIORITIES: 1 35 1` at the beginning of a buffer. For me, the cycling only ranges between 1 and 3. Looks like the 35 is parsed as 3. If it works for you, please let me know!~~

Edit: I had an outdated version of orgmode in my emacs. It works as expected.

### Minimal init.lua

```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup({
    {
      'wbthomason/packer.nvim',
      { 'nvim-treesitter/nvim-treesitter' },
      { 'kristijanhusak/orgmode.nvim', branch = 'master' },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  })
end

_G.load_config = function()
  require('orgmode').setup_ts_grammar()
  require('nvim-treesitter.configs').setup({
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'org' },
    },
  })
  require('orgmode').setup({
    org_priority_highest = '1',
    org_priority_default = '5',
    org_priority_lowest = '15'
  })

  vim.cmd([[packadd nvim-treesitter]])
  vim.cmd([[runtime plugin/nvim-treesitter.lua]])
  vim.cmd([[TSUpdateSync org]])

  -- Close packer after install
  if vim.bo.filetype == 'packer' then
    vim.api.nvim_win_close(0, true)
  end

  require('orgmode').setup()

  -- Reload current file if it's org file to reload tree-sitter
  if vim.bo.filetype == 'org' then
    vim.cmd([[edit!]])
  end
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path })
  load_plugins()
  require('packer').sync()
  vim.cmd([[autocmd User PackerCompileDone ++once lua load_config()]])
else
  load_plugins()
  load_config()
end
```

### Screenshots and recordings

prio-cycle

The bug is even more peculiar when doing reverse cycling with `ciR`:

reverse-prio-cycle

### OS / Distro

Ubuntu 20.04

### Neovim version/commit

0.7.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jgollenz**
fixes #382 

@kristijanhusak I'd like to hear your opinion on the validation of priorities provided by the users config. It's a bit messy I think.

### CODE REVIEW

**Comment by jgollenz** [comment]
Regarding the failed tests: if I read [this](https://orgmode.org/manual/Priorities.html) correctly, then [this](https://github.com/nvim-orgmode/orgmode/blob/77ea13332f3c811b707e902c7cb8605c471a2f4c/tests/plenary/object/priority_state_spec.lua#L15) is not correct. The highest priority should be the lowest number.

**Comment by jgollenz** [comment]
See, the input validation already paid off. Those unit tests were only working due to the bug I'm trying to fix :grin:

**Comment by jgollenz** [comment]
@kristijanhusak this should now work

**Review by kristijanhusak — APPROVED** [review]

**Comment by kristijanhusak** [comment]
Thanks!

**Pull request merged**
