### PR TITLE
Add refile_to_headline

### PR DESCRIPTION
**Pull request by joshpetit**
#196 

Haven't written a test yet but would appreciate feed back on whether it looks like a good implementation, thanks

### CODE REVIEW

**Comment by kristijanhusak** [comment]
This looks ok. I don't think you need to throw an error, just let it refile to the end of the file if there's no headline found.

**Comment by joshpetit** [comment]
just fixed the lint, I see that there are no tests yet, I'm pretty confused on how I would write one for this. Could you give me an example of how one might look here?  I've taken a look at the agenda and template spec.

**Comment by kristijanhusak** [comment]
It's a bit tricky to write tests for this because it manages multiple buffers. It's ok to not have test for this for now.

**Comment by kristijanhusak** [comment]
Looks good, thanks!

**Pull request merged**
