### PR TITLE
Use treesitter for buffer actions

### PR DESCRIPTION
**Pull request by TravonteD**
This PR is based on this discussion issue #271 
- [x] implement priority changing via treesitter
- [x] implement `TODO` keyword toggling via treesitter

### CODE REVIEW

**Comment by kristijanhusak** [comment]
This looks and works great!

This should simplify a lot of manual modification that I wrote initially before we had ts parser.

I would just like to have the code structured a bit differently. My idea is to have an encapsulated class for this. For example, instead of doing `tree_utils.set_todo(headline, next_state.value)` to have something like this:

``` lua
local headline = tree_utils.headline()
headline:set_todo(next_state.value)

-- Or

headline:set_priority(new_priority)
```

This is how it currently works with `Section`, but we could have something similar for these tree-sitter stuff, that doesn't require re-parsing file or anything, and maybe slowly migrating more things to this. What do you think?

**Comment by TravonteD** [comment]
> My idea is to have an encapsulated class for this.

Converting it to class style should be straight forward, I'll give it an update.


I agree with your last suggestion, I'd like to keep implementing small ui changes that can be done with treesitter, and we can migrate when it makes since.

**Comment by TravonteD** [comment]
I got a chance to look into the encapsulated style.
This:
```lua
tree_utils.set_todo(headline, next_state.value)
```
and this:
```lua
headline:set_todo(next_state.value)
```
are not equivalent because `tree_utils.get_closest_headline()` returns a `tsnode` (`:help lua-treesitter-node`). 
I'd prefer to have this not be something that holds state because the treesitter nodes already do that (via incremental parsing). After implementing a few functions I think that it'll make this much more complex to maintain.

**Comment by kristijanhusak** [comment]
Yeah, it's an instance by itself, but I would like to have a small wrapper around it so it's more readable, and later more extensible. For example to introduce something like `Headline` "class":
```lua
---@param headline userdata tree sitter headline node
function Headline:new(headline)
  local data = { headline = headline }
  setmetatable(data, self)
  self.__index = self
  return data
end

-- Using get_stars for sake of simplicity
function Headline:get_stars()
  return self.headline:field('stars')[1]
end
```

And in your tree_utils you can just initiate it after you find it:

```lua
-- returns the Headline instance
function M.headline()
  return Headline:new(M.get_closest_headline())
end
```

And then in the mappings you could do this:
```lua
local headline = tree_utils.headline()
return headline:set_priority(value)
```

headline tsnode is basically a dependency for most of these ts util functions, so it's easier to provide it once and have it available inside then to pass it each time as a dependency to each function.

**Comment by TravonteD** [comment]
I believe that I'm getting the gist of what you're saying, and I think it's just a matter of style preference. I mostly write in functional programming languages where encapsulation is achieved via different means. I'll finish up the implementation and set for review.

**Review by kristijanhusak — APPROVED** [review]
Looks good!

Thanks!

**Pull request merged**
