### PR TITLE
foldlevel should not be zero

### PR DESCRIPTION
**Pull request by WhiteBlackGoose**
Not sure if it's by design or not, but when it's zero it's extremely annoying bc it automatically folds everything once you leave insert mode.

### CODE REVIEW

**Comment by jgollenz** [comment]
The reason why it is set to zero isn't obvious to me either. But why would the foldlevel close your folds :thinking: doesn't happen for me

**Comment by kristijanhusak** [comment]
@WhiteBlackGoose are you maybe using nvim-ufo?

**Comment by WhiteBlackGoose** [comment]
Yeah i am

**Comment by kristijanhusak** [comment]
@WhiteBlackGoose can you check if it happens when you disable it? It should not happen without that plugin. I need to further investigate why it happens with it. I had issue with that plugin while resolving git conflicts via Neovim because it went crazy with folds in the diff files, so I'm suspecting this is more of an issue there.

**Comment by kristijanhusak** [comment]
Closing as duplicate (kind of) of https://github.com/nvim-orgmode/orgmode/issues/599

**Pull request closed without merging**
